language: node_js
node_js:
  - "lts/*"
addons:
sonarcloud:
  organization: "psmorrow-github"
  token:
    secure: "vabCA26pyxJ9WTrssIOhewPSkMabf8Axp6THrS4mKDaY/hicEcZ1ekzkMNQJJR9PXIxa/iYFhJn2QYmc6mjJCe94BFrvDI8Jz50BMqbXiq6i2VWqoDIewctuXdNQVdfkMqKA8l/42vKXcyNxvCiajU5u2V02MrsPSI8mMXSzA3AXSyLyqwJw36pEggqC2McjDFm/CsWvTMHDtej0yklYasOcdMkghkk76BLto0zsDSlW082pms8m2IwGKbmyL5N7U/Ppv43MHv4osqhlDjl4LieWc+FdvbGjQYzmv5Qw0fr0X6zMD5KmqzhiUPwAVTWlZKfqhx7C7TfZOST5MsfcmwfnH8OHP4KGTO6qNTGGR57U2uP/7acAR6hqeT47pAyBe54r1q57Y4WMP5ekPkl4mRCI5edqUEHc6ww5Tizf4/FfnGytzhV5wdkzVPxxhSyDzYDUeMXWBdEBRqldc3XQ20yejO/u1ATYwIS2tFYSbJ8G3Zm66z8R1dPtIp0PycIRKp5khM/zVGmbsA6roY/sr80LcRYUsf219Zb5MgONcwUrrtI5FYI4sMiimPuMTk0QLHcJTN+5LtibKfG//oLMdVekOd6iQnx3mRBiMGsHobGR6DhBZjGgLbPFZ392FbJB2jTuQJGZDz+w30VO8CES81Wqg1sHjvr8AaT8n/jy3F8="
script:
  - "npm run lint"
  - "npm test"
  - sonar-scanner
